# Generated by Django 4.2.7 on 2024-09-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_news1_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1000)),
                ('skills', models.CharField(max_length=10000)),
                ('posted_date', models.CharField(max_length=1000, null=True)),
                ('apply_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Add_your_news',
        ),
    ]
