# Generated by Django 5.0.1 on 2024-10-01 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_internship_delete_add_your_news"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contest",
        ),
        migrations.DeleteModel(
            name="Internship",
        ),
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.DeleteModel(
            name="News",
        ),
    ]
