# Generated by Django 5.0.1 on 2024-10-05 07:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companydetails",
            name="company_size",
        ),
        migrations.RemoveField(
            model_name="companydetails",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="companydetails",
            name="description",
        ),
        migrations.RemoveField(
            model_name="companydetails",
            name="revenue",
        ),
        migrations.RemoveField(
            model_name="contestdetails",
            name="link",
        ),
        migrations.RemoveField(
            model_name="internshipdetails",
            name="internshipDescription",
        ),
        migrations.RemoveField(
            model_name="internshipdetails",
            name="payRange",
        ),
        migrations.RemoveField(
            model_name="internshipdetails",
            name="qualifications",
        ),
        migrations.RemoveField(
            model_name="jobdetails",
            name="jobDescription",
        ),
        migrations.RemoveField(
            model_name="jobdetails",
            name="qualifications",
        ),
        migrations.RemoveField(
            model_name="newsdetails",
            name="link",
        ),
        migrations.RemoveField(
            model_name="newsdetails",
            name="percent",
        ),
        migrations.RemoveField(
            model_name="newsdetails",
            name="razor_pay_order_id",
        ),
        migrations.RemoveField(
            model_name="newsdetails",
            name="razor_pay_patment_signature",
        ),
        migrations.RemoveField(
            model_name="newsdetails",
            name="razor_pay_payment_id",
        ),
        migrations.RemoveField(
            model_name="newsdetails",
            name="user",
        ),
        migrations.AddField(
            model_name="companydetails",
            name="userId",
            field=models.ForeignKey(
                default=1111,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.users",
            ),
        ),
        migrations.AddField(
            model_name="contestdetails",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.companydetails",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contestdetails",
            name="contestUrl",
            field=models.URLField(default="http://example.com"),
        ),
        migrations.AddField(
            model_name="internshipdetails",
            name="category",
            field=models.CharField(default="Full-time", max_length=255),
        ),
        migrations.AddField(
            model_name="internshipdetails",
            name="description",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AddField(
            model_name="internshipdetails",
            name="duration",
            field=models.CharField(default="3 months", max_length=50),
        ),
        migrations.AddField(
            model_name="internshipdetails",
            name="expiryDate",
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internshipdetails",
            name="field",
            field=models.CharField(default="General", max_length=25),
        ),
        migrations.AddField(
            model_name="internshipdetails",
            name="postedOn",
            field=models.DateTimeField(
                auto_now_add=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internshipdetails",
            name="skills",
            field=models.TextField(default="No skills required"),
        ),
        migrations.AddField(
            model_name="internshipdetails",
            name="stipend",
            field=models.CharField(
                blank=True, default="Unpaid", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobdetails",
            name="category",
            field=models.CharField(default="Full-time", max_length=25),
        ),
        migrations.AddField(
            model_name="jobdetails",
            name="description",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AddField(
            model_name="jobdetails",
            name="duration",
            field=models.CharField(default="Permanent", max_length=50),
        ),
        migrations.AddField(
            model_name="jobdetails",
            name="expiryDate",
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobdetails",
            name="field",
            field=models.CharField(default="General", max_length=25),
        ),
        migrations.AddField(
            model_name="jobdetails",
            name="postedOn",
            field=models.DateTimeField(
                auto_now_add=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobdetails",
            name="skills",
            field=models.TextField(default="No skills required"),
        ),
        migrations.AddField(
            model_name="jobdetails",
            name="student_applied",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="newsdetails",
            name="news_url",
            field=models.URLField(default="http://example.com"),
        ),
        migrations.AlterField(
            model_name="companydetails",
            name="address",
            field=models.TextField(default="No address provided"),
        ),
        migrations.AlterField(
            model_name="companydetails",
            name="companyName",
            field=models.CharField(default="Unknown Company", max_length=255),
        ),
        migrations.AlterField(
            model_name="companydetails",
            name="email",
            field=models.EmailField(
                default="company@example.com", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="companydetails",
            name="industryType",
            field=models.CharField(default="Unknown Industry", max_length=100),
        ),
        migrations.AlterField(
            model_name="contestdetails",
            name="title",
            field=models.CharField(default="Untitled Contest", max_length=255),
        ),
        migrations.AlterField(
            model_name="internshipdetails",
            name="location",
            field=models.CharField(default="Remote", max_length=255),
        ),
        migrations.AlterField(
            model_name="jobdetails",
            name="location",
            field=models.CharField(default="Remote", max_length=255),
        ),
        migrations.AlterField(
            model_name="jobdetails",
            name="payRange",
            field=models.CharField(default="Not specified", max_length=100),
        ),
        migrations.AlterField(
            model_name="newsdetails",
            name="headline",
            field=models.CharField(default="Untitled Headline", max_length=255),
        ),
        migrations.AlterField(
            model_name="newsdetails",
            name="summary",
            field=models.TextField(default="No summary available"),
        ),
        migrations.CreateModel(
            name="companyDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companydetails",
                    ),
                ),
                (
                    "internships",
                    models.ManyToManyField(blank=True, to="company.internshipdetails"),
                ),
                ("jobs", models.ManyToManyField(blank=True, to="company.jobdetails")),
            ],
        ),
        migrations.CreateModel(
            name="jobApplication",
            fields=[
                (
                    "jobApplicationId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="Unknown Applicant", max_length=255)),
                (
                    "email",
                    models.EmailField(default="applicant@example.com", max_length=254),
                ),
                ("phoneNumber", models.BigIntegerField(default=1234567890)),
                (
                    "resume",
                    models.FileField(
                        default="applications/default_resume.pdf",
                        upload_to="applications/",
                    ),
                ),
                ("relevantWorkExperience", models.IntegerField(default=0)),
                (
                    "experienceCompanyName",
                    models.CharField(default="No experience", max_length=255),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.jobdetails",
                    ),
                ),
            ],
        ),
    ]
