# Generated by Django 5.0.1 on 2024-10-05 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_alter_companydetails_phonenumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internshipdetails",
            name="expiryDate",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="jobdetails",
            name="expiryDate",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
