# Generated by Django 5.0.1 on 2024-10-05 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0002_remove_companydetails_company_size_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="studentDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobs_applied", models.JSONField(default=dict)),
                ("internships_applied", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="jobTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("sent", "Sent to Company"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("interview", "Interview Scheduled"),
                            ("selected", "Selected"),
                            ("not_selected", "Not Selected"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("interview_or_exam_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.studentdashboard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="studentDetails",
            fields=[
                ("studentId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "studentName",
                    models.CharField(default="Unknown Student", max_length=50),
                ),
                (
                    "studentEmail",
                    models.EmailField(default="example@example.com", max_length=254),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("phoneNumber", models.BigIntegerField(default=1234567890)),
                ("college", models.CharField(default="Unknown College", max_length=50)),
                ("branch", models.CharField(default="Unknown Branch", max_length=50)),
                ("cgpa", models.FloatField(default=0.0, max_length=4)),
                ("internshipDone", models.BooleanField(default=False)),
                ("internshipData", models.TextField(blank=True, null=True)),
                (
                    "resume",
                    models.FileField(
                        default="resumes/default_resume.pdf", upload_to="resumes/"
                    ),
                ),
                ("github", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("open_source", models.BooleanField(default=False)),
                ("open_source_data", models.TextField(blank=True, null=True)),
                (
                    "userId",
                    models.ForeignKey(
                        default=11111,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentdashboard",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="student.studentdetails"
            ),
        ),
        migrations.CreateModel(
            name="studentBookmark",
            fields=[
                ("bookmarkId", models.AutoField(primary_key=True, serialize=False)),
                ("bookmarkDate", models.DateTimeField(auto_now_add=True)),
                (
                    "internships",
                    models.ManyToManyField(blank=True, to="company.internshipdetails"),
                ),
                ("jobs", models.ManyToManyField(blank=True, to="company.jobdetails")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.studentdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(default="No message", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.studentdetails",
                    ),
                ),
            ],
        ),
    ]
